// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` runs on every install and build (including CI and Vercel
// builds where no database is configured yet). It only needs a syntactically
// valid URL, so fall back to a placeholder rather than failing the build.
// Commands that actually connect (migrate, db push, studio, seed) still need a
// real DATABASE_URL in the environment.
const DATABASE_URL_PLACEHOLDER =
  "postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public";

if (!process.env.DATABASE_URL) {
  console.warn(
    "[prisma.config] DATABASE_URL is not set; using a placeholder so `prisma generate` can run."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? DATABASE_URL_PLACEHOLDER,
  },
});
